### ISSUE TITLE
KMeans is not executed on the GPU?

### ISSUE THREAD

**Issue by LfieLike** [HugoZHL/PQCache#1]
Thanks for your great work!
 During the inference process, the GPU utilization is relatively low. Could you kindly explain why  the KMeans algorithm is not performed asynchronously on the GPU? I am curious to understand the reasoning behind this design choice and whether there are specific considerations or limitations that influenced this decision.

**Comment by HugoZHL** [comment]
Thanks for your interest in our work. 
The inference process can be separated into 2 phases: the first is **prefilling**, which computes the whole input sentence and is compute-intensive; the second is **decoding**, which only computes the last generated token and is I/O-intensive. The results of KMeans is required by the decoding process, so we need to make them prepared before the decoding phase. In PQCache, we choose to put the KMeans on CPU, so that its computation can be overlapped with the compute-intensive prefilling. In practice, we also tried executing KMeans on GPU, and found that it will slow down the prefilling and increase the time for the first tokens.
